name: deepcubeai_env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python
  - matplotlib
  - pytorch
  - tensorboard
  - numpy
  - openmpi
  - mpi
  - scikit-learn
  - networkx
  - imageio
  - imageio-ffmpeg
  - gym
  - opencv
